-- 创建每日基础数据表
CREATE TABLE `base_info_day` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `stock_name` varchar(100) NOT NULL COMMENT '股票简称',
    `latest_price` decimal(10, 2) DEFAULT NULL COMMENT '最新价',
    `auction_change_rate` decimal(10, 3) DEFAULT NULL COMMENT '竞价涨幅(%)',
    `latest_change_rate` decimal(10, 2) DEFAULT NULL COMMENT '最新涨跌幅(%)',
    `auction_unmatched_amount_str` varchar(50) DEFAULT NULL COMMENT '竞价未匹配金额（带单位，如：284.11万、2.84亿）',
    `morning_auction_amount_str` varchar(50) DEFAULT '' COMMENT '早盘竞价金额(万/亿)',
    `turnover_str` varchar(50) DEFAULT '' COMMENT '成交额(万/亿)',
    `circulation_market_value` decimal(20, 2) DEFAULT NULL COMMENT '流通市值',
    `circulation_market_value_str` varchar(50) DEFAULT '' COMMENT '流通市值（如：12万、1.3亿）',
    `stock_code` varchar(20) NOT NULL COMMENT '股票代码（含后缀）',
    `trade_date` date NOT NULL COMMENT '交易日期',
    `market_code` varchar(10) DEFAULT NULL COMMENT '市场代码',
    `code` varchar(20) NOT NULL COMMENT '股票代码（不含后缀）',
    `turnover` decimal(20, 2) DEFAULT NULL COMMENT '成交额',
    `morning_auction_amount` bigint DEFAULT NULL COMMENT '早盘竞价金额',
    `auction_unmatched_amount` bigint DEFAULT NULL COMMENT '竞价未匹配金额（原始值）',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `company_highlights` text COMMENT '公司亮点',
    `industry_category` varchar(100) DEFAULT '' COMMENT '行业分类',
    `concept_theme` text COMMENT '概念题材',
    `consecutive_limit_days` int DEFAULT '0' COMMENT '连板天数',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_code_date` (`code`, `trade_date`),
    KEY `idx_code` (`code`),
    KEY `idx_stock_code` (`stock_code`),
    KEY `idx_trade_date` (`trade_date`)
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '每日基础数据表';
