// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/stock.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stock 股票信息
type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,6,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	Turnover      float64                `protobuf:"fixed64,7,opt,name=turnover,proto3" json:"turnover,omitempty"`
	MarketValue   float64                `protobuf:"fixed64,8,opt,name=market_value,json=marketValue,proto3" json:"market_value,omitempty"`
	BoardDays     int32                  `protobuf:"varint,9,opt,name=board_days,json=boardDays,proto3" json:"board_days,omitempty"`
	LimitReason   string                 `protobuf:"bytes,10,opt,name=limit_reason,json=limitReason,proto3" json:"limit_reason,omitempty"`
	Highlights    string                 `protobuf:"bytes,11,opt,name=highlights,proto3" json:"highlights,omitempty"`
	Industry      string                 `protobuf:"bytes,12,opt,name=industry,proto3" json:"industry,omitempty"`
	Concepts      string                 `protobuf:"bytes,13,opt,name=concepts,proto3" json:"concepts,omitempty"`
	PreClose      float64                `protobuf:"fixed64,14,opt,name=pre_close,json=preClose,proto3" json:"pre_close,omitempty"`
	Open          float64                `protobuf:"fixed64,15,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,16,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,17,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,18,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,19,opt,name=volume,proto3" json:"volume,omitempty"`
	BidAmount     float64                `protobuf:"fixed64,20,opt,name=bid_amount,json=bidAmount,proto3" json:"bid_amount,omitempty"`
	BidUnmatched  float64                `protobuf:"fixed64,21,opt,name=bid_unmatched,json=bidUnmatched,proto3" json:"bid_unmatched,omitempty"`
	BidChange     float64                `protobuf:"fixed64,22,opt,name=bid_change,json=bidChange,proto3" json:"bid_change,omitempty"`
	SealAmount    float64                `protobuf:"fixed64,23,opt,name=seal_amount,json=sealAmount,proto3" json:"seal_amount,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,24,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,25,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_api_proto_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_proto_rawDescGZIP(), []int{0}
}

func (x *Stock) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Stock) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Stock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stock) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Stock) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Stock) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *Stock) GetTurnover() float64 {
	if x != nil {
		return x.Turnover
	}
	return 0
}

func (x *Stock) GetMarketValue() float64 {
	if x != nil {
		return x.MarketValue
	}
	return 0
}

func (x *Stock) GetBoardDays() int32 {
	if x != nil {
		return x.BoardDays
	}
	return 0
}

func (x *Stock) GetLimitReason() string {
	if x != nil {
		return x.LimitReason
	}
	return ""
}

func (x *Stock) GetHighlights() string {
	if x != nil {
		return x.Highlights
	}
	return ""
}

func (x *Stock) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *Stock) GetConcepts() string {
	if x != nil {
		return x.Concepts
	}
	return ""
}

func (x *Stock) GetPreClose() float64 {
	if x != nil {
		return x.PreClose
	}
	return 0
}

func (x *Stock) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Stock) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Stock) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Stock) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Stock) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Stock) GetBidAmount() float64 {
	if x != nil {
		return x.BidAmount
	}
	return 0
}

func (x *Stock) GetBidUnmatched() float64 {
	if x != nil {
		return x.BidUnmatched
	}
	return 0
}

func (x *Stock) GetBidChange() float64 {
	if x != nil {
		return x.BidChange
	}
	return 0
}

func (x *Stock) GetSealAmount() float64 {
	if x != nil {
		return x.SealAmount
	}
	return 0
}

func (x *Stock) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Stock) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// QueryStocksRequest 查询股票请求
type QueryStocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStocksRequest) Reset() {
	*x = QueryStocksRequest{}
	mi := &file_api_proto_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStocksRequest) ProtoMessage() {}

func (x *QueryStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStocksRequest.ProtoReflect.Descriptor instead.
func (*QueryStocksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_proto_rawDescGZIP(), []int{1}
}

func (x *QueryStocksRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *QueryStocksRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *QueryStocksRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *QueryStocksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryStocksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// QueryStocksResponse 查询股票响应
type QueryStocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Stocks        []*Stock               `protobuf:"bytes,4,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStocksResponse) Reset() {
	*x = QueryStocksResponse{}
	mi := &file_api_proto_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStocksResponse) ProtoMessage() {}

func (x *QueryStocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStocksResponse.ProtoReflect.Descriptor instead.
func (*QueryStocksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_proto_rawDescGZIP(), []int{2}
}

func (x *QueryStocksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryStocksResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryStocksResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *QueryStocksResponse) GetStocks() []*Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

// GetLatestStocksRequest 获取最新股票请求
type GetLatestStocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestStocksRequest) Reset() {
	*x = GetLatestStocksRequest{}
	mi := &file_api_proto_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestStocksRequest) ProtoMessage() {}

func (x *GetLatestStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestStocksRequest.ProtoReflect.Descriptor instead.
func (*GetLatestStocksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatestStocksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetLatestStocksResponse 获取最新股票响应
type GetLatestStocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Stocks        []*Stock               `protobuf:"bytes,2,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestStocksResponse) Reset() {
	*x = GetLatestStocksResponse{}
	mi := &file_api_proto_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestStocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestStocksResponse) ProtoMessage() {}

func (x *GetLatestStocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestStocksResponse.ProtoReflect.Descriptor instead.
func (*GetLatestStocksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestStocksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetLatestStocksResponse) GetStocks() []*Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

// TriggerFetchRequest 触发抓取请求
type TriggerFetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerFetchRequest) Reset() {
	*x = TriggerFetchRequest{}
	mi := &file_api_proto_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerFetchRequest) ProtoMessage() {}

func (x *TriggerFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerFetchRequest.ProtoReflect.Descriptor instead.
func (*TriggerFetchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_proto_rawDescGZIP(), []int{5}
}

// TriggerFetchResponse 触发抓取响应
type TriggerFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FetchedCount  int32                  `protobuf:"varint,3,opt,name=fetched_count,json=fetchedCount,proto3" json:"fetched_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerFetchResponse) Reset() {
	*x = TriggerFetchResponse{}
	mi := &file_api_proto_stock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerFetchResponse) ProtoMessage() {}

func (x *TriggerFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerFetchResponse.ProtoReflect.Descriptor instead.
func (*TriggerFetchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_stock_proto_rawDescGZIP(), []int{6}
}

func (x *TriggerFetchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerFetchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TriggerFetchResponse) GetFetchedCount() int32 {
	if x != nil {
		return x.FetchedCount
	}
	return 0
}

var File_api_proto_stock_proto protoreflect.FileDescriptor

const file_api_proto_stock_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/stock.proto\x12\bstock.v1\"\xb0\x05\n" +
	"\x05Stock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12%\n" +
	"\x0echange_percent\x18\x06 \x01(\x01R\rchangePercent\x12\x1a\n" +
	"\bturnover\x18\a \x01(\x01R\bturnover\x12!\n" +
	"\fmarket_value\x18\b \x01(\x01R\vmarketValue\x12\x1d\n" +
	"\n" +
	"board_days\x18\t \x01(\x05R\tboardDays\x12!\n" +
	"\flimit_reason\x18\n" +
	" \x01(\tR\vlimitReason\x12\x1e\n" +
	"\n" +
	"highlights\x18\v \x01(\tR\n" +
	"highlights\x12\x1a\n" +
	"\bindustry\x18\f \x01(\tR\bindustry\x12\x1a\n" +
	"\bconcepts\x18\r \x01(\tR\bconcepts\x12\x1b\n" +
	"\tpre_close\x18\x0e \x01(\x01R\bpreClose\x12\x12\n" +
	"\x04open\x18\x0f \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x10 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x11 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x12 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x13 \x01(\x01R\x06volume\x12\x1d\n" +
	"\n" +
	"bid_amount\x18\x14 \x01(\x01R\tbidAmount\x12#\n" +
	"\rbid_unmatched\x18\x15 \x01(\x01R\fbidUnmatched\x12\x1d\n" +
	"\n" +
	"bid_change\x18\x16 \x01(\x01R\tbidChange\x12\x1f\n" +
	"\vseal_amount\x18\x17 \x01(\x01R\n" +
	"sealAmount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x18 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x19 \x01(\tR\tupdatedAt\"\x93\x01\n" +
	"\x12QueryStocksRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"|\n" +
	"\x13QueryStocksResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12'\n" +
	"\x06stocks\x18\x04 \x03(\v2\x0f.stock.v1.StockR\x06stocks\".\n" +
	"\x16GetLatestStocksRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"X\n" +
	"\x17GetLatestStocksResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12'\n" +
	"\x06stocks\x18\x02 \x03(\v2\x0f.stock.v1.StockR\x06stocks\"\x15\n" +
	"\x13TriggerFetchRequest\"o\n" +
	"\x14TriggerFetchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rfetched_count\x18\x03 \x01(\x05R\ffetchedCount2\x81\x02\n" +
	"\fStockService\x12J\n" +
	"\vQueryStocks\x12\x1c.stock.v1.QueryStocksRequest\x1a\x1d.stock.v1.QueryStocksResponse\x12V\n" +
	"\x0fGetLatestStocks\x12 .stock.v1.GetLatestStocksRequest\x1a!.stock.v1.GetLatestStocksResponse\x12M\n" +
	"\fTriggerFetch\x12\x1d.stock.v1.TriggerFetchRequest\x1a\x1e.stock.v1.TriggerFetchResponseB3Z1github.com/iamloso/goweicai/api/proto/stock/v1;v1b\x06proto3"

var (
	file_api_proto_stock_proto_rawDescOnce sync.Once
	file_api_proto_stock_proto_rawDescData []byte
)

func file_api_proto_stock_proto_rawDescGZIP() []byte {
	file_api_proto_stock_proto_rawDescOnce.Do(func() {
		file_api_proto_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_stock_proto_rawDesc), len(file_api_proto_stock_proto_rawDesc)))
	})
	return file_api_proto_stock_proto_rawDescData
}

var file_api_proto_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_stock_proto_goTypes = []any{
	(*Stock)(nil),                   // 0: stock.v1.Stock
	(*QueryStocksRequest)(nil),      // 1: stock.v1.QueryStocksRequest
	(*QueryStocksResponse)(nil),     // 2: stock.v1.QueryStocksResponse
	(*GetLatestStocksRequest)(nil),  // 3: stock.v1.GetLatestStocksRequest
	(*GetLatestStocksResponse)(nil), // 4: stock.v1.GetLatestStocksResponse
	(*TriggerFetchRequest)(nil),     // 5: stock.v1.TriggerFetchRequest
	(*TriggerFetchResponse)(nil),    // 6: stock.v1.TriggerFetchResponse
}
var file_api_proto_stock_proto_depIdxs = []int32{
	0, // 0: stock.v1.QueryStocksResponse.stocks:type_name -> stock.v1.Stock
	0, // 1: stock.v1.GetLatestStocksResponse.stocks:type_name -> stock.v1.Stock
	1, // 2: stock.v1.StockService.QueryStocks:input_type -> stock.v1.QueryStocksRequest
	3, // 3: stock.v1.StockService.GetLatestStocks:input_type -> stock.v1.GetLatestStocksRequest
	5, // 4: stock.v1.StockService.TriggerFetch:input_type -> stock.v1.TriggerFetchRequest
	2, // 5: stock.v1.StockService.QueryStocks:output_type -> stock.v1.QueryStocksResponse
	4, // 6: stock.v1.StockService.GetLatestStocks:output_type -> stock.v1.GetLatestStocksResponse
	6, // 7: stock.v1.StockService.TriggerFetch:output_type -> stock.v1.TriggerFetchResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_stock_proto_init() }
func file_api_proto_stock_proto_init() {
	if File_api_proto_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_stock_proto_rawDesc), len(file_api_proto_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_stock_proto_goTypes,
		DependencyIndexes: file_api_proto_stock_proto_depIdxs,
		MessageInfos:      file_api_proto_stock_proto_msgTypes,
	}.Build()
	File_api_proto_stock_proto = out.File
	file_api_proto_stock_proto_goTypes = nil
	file_api_proto_stock_proto_depIdxs = nil
}
