// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/proto/stock.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StockService_QueryStocks_FullMethodName     = "/stock.v1.StockService/QueryStocks"
	StockService_GetLatestStocks_FullMethodName = "/stock.v1.StockService/GetLatestStocks"
	StockService_TriggerFetch_FullMethodName    = "/stock.v1.StockService/TriggerFetch"
)

// StockServiceClient is the client API for StockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StockService 股票服务
type StockServiceClient interface {
	// QueryStocks 查询股票
	QueryStocks(ctx context.Context, in *QueryStocksRequest, opts ...grpc.CallOption) (*QueryStocksResponse, error)
	// GetLatestStocks 获取最新股票
	GetLatestStocks(ctx context.Context, in *GetLatestStocksRequest, opts ...grpc.CallOption) (*GetLatestStocksResponse, error)
	// TriggerFetch 手动触发数据抓取
	TriggerFetch(ctx context.Context, in *TriggerFetchRequest, opts ...grpc.CallOption) (*TriggerFetchResponse, error)
}

type stockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStockServiceClient(cc grpc.ClientConnInterface) StockServiceClient {
	return &stockServiceClient{cc}
}

func (c *stockServiceClient) QueryStocks(ctx context.Context, in *QueryStocksRequest, opts ...grpc.CallOption) (*QueryStocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryStocksResponse)
	err := c.cc.Invoke(ctx, StockService_QueryStocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) GetLatestStocks(ctx context.Context, in *GetLatestStocksRequest, opts ...grpc.CallOption) (*GetLatestStocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestStocksResponse)
	err := c.cc.Invoke(ctx, StockService_GetLatestStocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) TriggerFetch(ctx context.Context, in *TriggerFetchRequest, opts ...grpc.CallOption) (*TriggerFetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerFetchResponse)
	err := c.cc.Invoke(ctx, StockService_TriggerFetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockServiceServer is the server API for StockService service.
// All implementations must embed UnimplementedStockServiceServer
// for forward compatibility.
//
// StockService 股票服务
type StockServiceServer interface {
	// QueryStocks 查询股票
	QueryStocks(context.Context, *QueryStocksRequest) (*QueryStocksResponse, error)
	// GetLatestStocks 获取最新股票
	GetLatestStocks(context.Context, *GetLatestStocksRequest) (*GetLatestStocksResponse, error)
	// TriggerFetch 手动触发数据抓取
	TriggerFetch(context.Context, *TriggerFetchRequest) (*TriggerFetchResponse, error)
	mustEmbedUnimplementedStockServiceServer()
}

// UnimplementedStockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockServiceServer struct{}

func (UnimplementedStockServiceServer) QueryStocks(context.Context, *QueryStocksRequest) (*QueryStocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryStocks not implemented")
}
func (UnimplementedStockServiceServer) GetLatestStocks(context.Context, *GetLatestStocksRequest) (*GetLatestStocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestStocks not implemented")
}
func (UnimplementedStockServiceServer) TriggerFetch(context.Context, *TriggerFetchRequest) (*TriggerFetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerFetch not implemented")
}
func (UnimplementedStockServiceServer) mustEmbedUnimplementedStockServiceServer() {}
func (UnimplementedStockServiceServer) testEmbeddedByValue()                      {}

// UnsafeStockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockServiceServer will
// result in compilation errors.
type UnsafeStockServiceServer interface {
	mustEmbedUnimplementedStockServiceServer()
}

func RegisterStockServiceServer(s grpc.ServiceRegistrar, srv StockServiceServer) {
	// If the following call panics, it indicates UnimplementedStockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockService_ServiceDesc, srv)
}

func _StockService_QueryStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).QueryStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_QueryStocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).QueryStocks(ctx, req.(*QueryStocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_GetLatestStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestStocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).GetLatestStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_GetLatestStocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).GetLatestStocks(ctx, req.(*GetLatestStocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_TriggerFetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerFetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).TriggerFetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_TriggerFetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).TriggerFetch(ctx, req.(*TriggerFetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StockService_ServiceDesc is the grpc.ServiceDesc for StockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stock.v1.StockService",
	HandlerType: (*StockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryStocks",
			Handler:    _StockService_QueryStocks_Handler,
		},
		{
			MethodName: "GetLatestStocks",
			Handler:    _StockService_GetLatestStocks_Handler,
		},
		{
			MethodName: "TriggerFetch",
			Handler:    _StockService_TriggerFetch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/stock.proto",
}
